// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvaImuAQ71iLqJFFfKOrjnaoZiTLIAsgk',
    appId: '1:179866435577:web:41f1a03964aff2b43ac728',
    messagingSenderId: '179866435577',
    projectId: 'spoco-app-9ad0a',
    authDomain: 'spoco-app-9ad0a.firebaseapp.com',
    storageBucket: 'spoco-app-9ad0a.appspot.com',
    measurementId: 'G-ZB4SKKDFPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVIAkvZcGDWeWUVfJ5WW_R-P-vKs8-6l8',
    appId: '1:179866435577:android:770d189347dd7b773ac728',
    messagingSenderId: '179866435577',
    projectId: 'spoco-app-9ad0a',
    storageBucket: 'spoco-app-9ad0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVo7o8Qvs7DiIehDs2IH-eeEaI9A6X7W8',
    appId: '1:179866435577:ios:02e5d7862b14beb03ac728',
    messagingSenderId: '179866435577',
    projectId: 'spoco-app-9ad0a',
    storageBucket: 'spoco-app-9ad0a.appspot.com',
    iosBundleId: 'com.example.spocoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVo7o8Qvs7DiIehDs2IH-eeEaI9A6X7W8',
    appId: '1:179866435577:ios:02e5d7862b14beb03ac728',
    messagingSenderId: '179866435577',
    projectId: 'spoco-app-9ad0a',
    storageBucket: 'spoco-app-9ad0a.appspot.com',
    iosBundleId: 'com.example.spocoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvaImuAQ71iLqJFFfKOrjnaoZiTLIAsgk',
    appId: '1:179866435577:web:17665978e5467dbe3ac728',
    messagingSenderId: '179866435577',
    projectId: 'spoco-app-9ad0a',
    authDomain: 'spoco-app-9ad0a.firebaseapp.com',
    storageBucket: 'spoco-app-9ad0a.appspot.com',
    measurementId: 'G-EYGPTJ0KSN',
  );
}
